# This file adds references to ZombieLib because the references keep getting autogenerated away
# This file should be deleted as soon as Russell properly adds the reference to ZombieLib in Unity
dotnet add Client/Assembly-CSharp.csproj reference ZombieLib/ZombieLib.csproj
dotnet add Server/Assembly-CSharp.csproj reference ZombieLib/ZombieLib.csproj
