services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.6
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # HTTP
      - target: 80
        published: 80
        mode: host
      # HTTPS
      - target: 443
        published: 443
        mode: host
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik-public-certificates:/certificates
    deploy:
      placement:
        constraints:
          # Make the traefik service run only on the node with this label
          # as the node with it has the volume for the certificates
          - node.labels.traefik-public.traefik-public-certificates == true
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constrain-label=traefik-public

        ##### HTTP
        #### Middleware config
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        ### Routers
        ## HTTP (redirect to https)
        - traefik.http.routers.traefik-public-http.rule=Host(`${DOMAIN}`)
        - traefik.http.routers.traefik-public-http.entrypoints=http
        - traefik.http.routers.traefik-public-http.middlewares=https-redirect
        ## HTTPS (The actual router)
        - traefik.http.routers.traefik-public-https.rule=HOST(`${DOMAIN}`)
        - traefik.http.routers.traefik-public.https.entrypoint=https
        - traefik.http.routers.traefik-public-https.tls=true
        # Let's Encrypt (le) TLS provider
        - traefik.http.routers.traefik-public-https.tls.certresolver=le

  frontend:
    build:
      context: ./crashblox
    labels:
      - "traefik.http.routers.frontend.rule=Host(`${DOMAIN}`)"
    environment:
      - DOMAIN=$DOMAIN

  identity:
    build:
      context: ./identity
    labels:
      - "traefik.http.routers.identity.rule=Host(`id.${DOMAIN}`)"
    env_file:
      - .env
    environment:
      - SERVER_NAME=id.${DOMAIN}
      - SERVER_HOST=http://id.${DOMAIN}
