services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.6
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  frontend:
    build:
      context: ./crashblox
    labels:
      - "traefik.http.routers.frontend.rule=Host(`${DOMAIN}`)"
    environment:
      - DOMAIN=$DOMAIN

  identity:
    build:
      context: ./identity
    labels:
      - "traefik.http.routers.identity.rule=Host(`id.${DOMAIN}`)"
    env_file:
      - .env
    environment:
      - SERVER_NAME=id.${DOMAIN}
      - SERVER_HOST=http://id.${DOMAIN}
