#traefik.yml
entryPoints:
  http:
    address: :80

providers:
  file:
    filename: "/etc/traefik/traefik-dynamic.yml"

# For testing purposes, go to localhost:8080 to see traefik stuff
api:
  dashboard: true
  insecure: true